list_mot = [
    "arbre", "maison", "chien", "chat", "ordinateur", "girafe", "banane", "voiture", "football", "montagne","gentil","orange",
    "soleil", "plage", "oiseau", "fleur", "bateau", "etoile", "lune", "musique", "livre", "pizza", "restaurant","vert","jaune","rouge",
    "famille", "amis", "vacances", "ecole", "crayon", "ciseaux", "papier", "couleur", "jardin", "hiver", "printemps",
    "ete", "automne", "internet", "telephone", "basketball", "tennis", "soccer", "volleyball", "escargot","table","chaise","tableau",
    "papillon", "serpent", "loup", "elephant", "tigre", "requin", "abeille", "dragon", "licorne", "dinosaure",
    "parapluie", "arcenciel", "chateau", "chapeau", "fusee", "astronaute", "galaxie", "extraterrestre","bonjour","golf",
    "laboratoire", "scientifique", "equation", "formule", "camera", "microscope", "telescope", "astronomie",
    "biologie", "chimie", "physique", "mathematiques", "litterature", "histoire", "geographie", "politique",
    "economie", "sociologie", "psychologie", "philosophie", "religion", "cuisine", "restaurant", "cuisinier",
    "gourmet", "gateau", "chocolat", "bonbon", "glace", "limonade", "cafe", "the", "jus", "eau", "piscine",
    "plongee", "surf", "skateboard", "velo", "randonnee", "montagnesrusses", "parcdattractions", "zoo","majeur",
    "foret", "ocean", "pluie", "tempete", "neige", "vent", "eclair", "tonnerre", "nuage", "arcenciel", "etoiles",
    "planete", "satellite", "comete", "astronaute", "exploration", "aventure", "decouverte", "invention",
    "experience", "laboratoire", "reussite", "chance", "malchance", "opportunite", "espoir", "reve", "cauchemar",
    "fantome", "vampire", "zombie", "sorciere", "sorcier", "fee", "magie", "mystere", "enigme", "aventurier",
    "hero", "villain", "superheros", "supervilain", "combat", "epee", "bouclier", "armure", "arc", "fleche",
    "magicien", "potion", "sortilege", "foretenchantee", "chateauhante", "tresor", "explorateur", "compagnon",
    "allie", "ennemi", "conquete", "victoire", "defaite", "bataille", "guerre", "paix", "amour", "amitie", "famille",
    "travail", "succes", "echec", "espoir", "desespoir", "joie", "tristesse", "colere", "peur", "courage",
    "resilience", "sante", "maladie", "medecine", "hopital", "docteur", "infirmiere", "patient", "vaccin",
    "epidemie", "pandemie", "histoire", "mythe", "legende", "conte", "poesie", "theatre", "cinema", "art",
    "peinture", "sculpture", "musee", "danse", "musique","avoir", "faire", "dire", "aller", "venir", "penser", "donner", "vouloir", "entendre",
    "parler", "mettre", "savoir", "regarder", "ecouter", "rester", "devoir", "vivre", "mourir", "ecrire",
    "venir", "partir", "appeler", "pousser", "conduire", "prendre", "avancer", "chercher", "choisir",
    "continuer", "demander", "gagner", "grandir", "imaginer", "jouer", "manger", "marcher", "obtenir",
    "ouvrir", "perdre", "placer", "repondre", "sauter", "trouver", "utiliser", "voler", "attacher",
    "bouger", "cacher", "changer", "commencer", "construire", "courir", "couvrir", "crier", "diner",
    "echanger", "enseigner", "entrer", "exprimer", "frapper", "habiter", "ignorer", "observer", "oublier",
    "supporter"
]